<x-layouts.app title="Users - INTSEC" wide>
    <div class="ops-page">
        <x-ui.page-header kicker="Access administration" title="Users" description="Security operations workspace for managing account access, roles, and availability."><x-slot:actions><a href="{{ route('users.create') }}" class="ops-button ops-button--primary">Create user</a></x-slot:actions></x-ui.page-header>
        @if (session('status'))<div class="ops-banner ops-banner--success" role="status">User operation completed.</div>@endif
        @error('user')<div class="ops-banner ops-banner--danger" role="alert">{{ $message }}</div>@enderror
        <form method="GET" class="ops-filter" aria-label="Filter users"><div class="ops-filter-heading"><div><h2 class="ops-filter-title">Account filters</h2><p class="ops-filter-state">Search identity, role, and account state.</p></div></div><div class="ops-filter-grid"><label class="ops-field ops-field--search"><span class="ops-label">Search</span><input name="search" value="{{ request('search') }}" placeholder="Name or email address"></label><label class="ops-field"><span class="ops-label">Role</span><select name="role"><option value="">All roles</option><option value="administrator" @selected(request('role') === 'administrator')>Administrators</option><option value="standard_user" @selected(request('role') === 'standard_user')>Standard users</option></select></label><label class="ops-field"><span class="ops-label">Status</span><select name="status"><option value="">All statuses</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select></label><div class="ops-filter-actions"><a class="ops-button ops-button--quiet" href="{{ route('users.index') }}">Clear</a><button class="ops-button ops-button--secondary">Apply filters</button></div></div></form>
        <section class="ops-table-shell"><div class="ops-panel-header"><div><h2 class="ops-panel-title">User accounts</h2><p class="ops-panel-description">Authorization and account availability.</p></div></div><div class="ops-table-scroll"><table class="ops-table ops-table--wide"><caption>Filtered INTSEC user accounts</caption><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Created</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>@forelse($users as $managedUser)<tr><td><a class="ops-panel-link" href="{{ route('users.show', $managedUser) }}">{{ $managedUser->name }}</a><span class="ops-cell-meta ops-wrap-anywhere">{{ $managedUser->email }}</span></td><td>{{ $managedUser->isAdministrator() ? 'Administrator' : 'Standard user' }}</td><td><span class="ops-badge {{ $managedUser->is_active ? 'ops-badge--green' : 'ops-badge--muted' }}">{{ $managedUser->is_active ? 'Active' : 'Inactive' }}</span></td><td>{{ $managedUser->created_at?->format('M j, Y') }}</td><td><a class="ops-button ops-button--quiet" href="{{ route('users.edit', $managedUser) }}">Edit</a></td></tr>@empty<tr><td colspan="5"><x-ui.empty-state title="No users found" description="No accounts match the current filters." /></td></tr>@endforelse</tbody></table></div><div class="ops-pagination">{{ $users->withQueryString()->links() }}</div></section>
    </div>
</x-layouts.app>
