<x-layouts.app title="Audit logs - INTSEC">
    <div class="ops-page">
        <x-ui.page-header kicker="Administration" title="Audit logs" description="Accountability records for administrative and security-sensitive operations.">
            <x-slot:context><span class="ops-context-pill">Immutable operational history</span></x-slot:context>
            <x-slot:actions><a href="{{ route('admin.settings') }}" class="ops-button ops-button--quiet">System settings</a></x-slot:actions>
        </x-ui.page-header>
        <form method="GET" class="ops-filter" aria-label="Search audit logs"><div class="ops-filter-heading"><div><h2 class="ops-filter-title">Audit search</h2><p class="ops-filter-state">Find an action, actor, resource, or originating IP.</p></div></div><div class="ops-filter-grid"><label class="ops-field ops-field--search"><span class="ops-label">Search records</span><input name="search" value="{{ request('search') }}" placeholder="Action, actor, resource, or IP"></label><div class="ops-filter-actions"><a class="ops-button ops-button--quiet" href="{{ route('admin.audit-logs') }}">Clear</a><button class="ops-button ops-button--secondary">Search</button></div></div></form>
        <section class="ops-table-shell" aria-labelledby="audit-table-title"><div class="ops-panel-header"><div><h2 id="audit-table-title" class="ops-panel-title">Recorded actions</h2><p class="ops-panel-description">Most recent security and administrative activity.</p></div></div><div class="ops-table-scroll"><table class="ops-table ops-table--wide"><caption>Administrative audit records</caption><thead><tr><th>Action</th><th>Performed by</th><th>Resource</th><th>Origin IP</th><th>Occurred</th></tr></thead><tbody>
            @forelse ($logs as $log)<tr><td><span class="ops-cell-primary">{{ str_replace('_', ' ', ucfirst($log->action)) }}</span></td><td>{{ $log->actor?->name ?? 'System' }}</td><td><span class="ops-technical ops-wrap-anywhere">{{ $log->resource_type ?? 'Not recorded' }}</span></td><td><span class="ops-technical ops-wrap-anywhere">{{ $log->ip_address ?? 'Unknown' }}</span></td><td><time datetime="{{ $log->occurred_at?->toIso8601String() }}">{{ $log->occurred_at?->format('M j, Y H:i:s') }}</time></td></tr>@empty<tr><td colspan="5"><x-ui.empty-state title="No audit records found" description="No records match the current search." /></td></tr>@endforelse
        </tbody></table></div><div class="ops-pagination">{{ $logs->withQueryString()->links() }}</div></section>
    </div>
</x-layouts.app>
