<x-layouts.app title="IP Request Frequency - INTSEC" wide>
    <header><p class="text-xs uppercase tracking-[0.2em] text-cyan-400">{{ $monitoringSource->label() }} request telemetry</p><h1 class="mt-2 text-3xl font-semibold text-white">IP Request Frequency</h1><p class="mt-2 text-sm text-zinc-400">Read-only aggregation of {{ $monitoringSource->label() }} application requests. Viewing this page does not run detection.</p></header>
    <form method="GET" class="mt-6 grid gap-3 rounded-lg border border-zinc-800 bg-zinc-900/60 p-4 sm:grid-cols-2 xl:grid-cols-5">
        <input name="ip" value="{{ request('ip') }}" placeholder="IP contains…" class="rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm">
        <select name="range" class="rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm">@foreach (['1h'=>'Last hour','24h'=>'Last 24 hours','7d'=>'Last 7 days','30d'=>'Last 30 days'] as $value=>$label)<option value="{{ $value }}" @selected(request('range','7d')===$value)>{{ $label }}</option>@endforeach</select>
        <select name="classification" class="rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><option value="">All classifications</option>@foreach (['normal','suspicious','malicious'] as $value)<option value="{{ $value }}" @selected(request('classification')===$value)>{{ ucfirst($value) }}</option>@endforeach</select>
        <select name="status_family" class="rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><option value="">All statuses</option>@foreach (['2xx','3xx','4xx','5xx'] as $value)<option value="{{ $value }}" @selected(request('status_family')===$value)>{{ $value }}</option>@endforeach</select>
        <div class="flex gap-2"><button class="flex-1 rounded-md bg-cyan-400 px-3 py-2 text-sm font-semibold text-zinc-950">Filter</button><a href="{{ auth()->user()->isAdministrator() ? route('monitoring.attack-frequency', $monitoringSource->value) : route('attack-frequency') }}" class="rounded-md border border-zinc-700 px-3 py-2 text-sm text-zinc-300">Clear</a></div>
    </form>
    <section class="mt-6 overflow-hidden rounded-lg border border-zinc-800 bg-zinc-900/60"><div class="overflow-x-auto"><table class="min-w-[1000px] w-full text-left text-sm"><thead class="border-b border-zinc-800 text-xs uppercase tracking-wider text-zinc-500"><tr><th class="px-4 py-3">IP</th><th class="px-4 py-3">Requests</th><th class="px-4 py-3">Last seen</th><th class="px-4 py-3">Top path</th><th class="px-4 py-3">4xx / 403 / 404</th><th class="px-4 py-3">Class</th><th class="px-4 py-3">Policy</th></tr></thead><tbody class="divide-y divide-zinc-800">@forelse ($attackFrequency as $row)<tr><td class="px-4 py-3 font-mono text-zinc-200">{{ $row['ip'] }}</td><td class="px-4 py-3">{{ number_format($row['count']) }}</td><td class="px-4 py-3 text-zinc-400">{{ \Carbon\Carbon::parse($row['last_seen'])->diffForHumans() }}</td><td class="max-w-xs truncate px-4 py-3 font-mono text-zinc-400">{{ $row['route'] ?? '—' }}</td><td class="px-4 py-3 text-zinc-400">{{ $row['client_errors'] }} / {{ $row['forbidden_count'] }} / {{ $row['not_found_count'] }}</td><td class="px-4 py-3">{{ ucfirst($row['classification'] ?? 'normal') }} · {{ ucfirst($row['ip_type']) }}</td><td class="px-4 py-3 {{ $row['is_blocked'] ? 'text-red-300' : 'text-zinc-500' }}">{{ $row['is_blocked'] ? 'Blocked' : 'No block' }}</td></tr>@empty<tr><td colspan="7" class="px-4 py-10 text-center text-zinc-500">No request telemetry matches these filters.</td></tr>@endforelse</tbody></table></div></section>
    <div class="mt-6">{{ $attackFrequency->links() }}</div>
</x-layouts.app>
