<x-layouts.app title="Profile and security - INTSEC">
    <div class="ops-page">
        <x-ui.page-header kicker="Account security" title="Profile and security" description="Manage your identity, password, authenticator, and emergency recovery options."><x-slot:context><span class="ops-context-pill ops-context-pill--live">Two-factor authentication enabled</span></x-slot:context></x-ui.page-header>
        @if (session('status'))<div class="ops-banner ops-banner--success" role="status">Security settings updated successfully.</div>@endif
        @if ($errors->any())<div class="ops-banner ops-banner--danger" role="alert">{{ $errors->first() }}</div>@endif
        <div class="ops-split-layout">
            <div class="ops-stack">
                <section class="ops-panel ops-panel--padded"><div class="ops-panel-header"><div><h2 class="ops-panel-title">Account information</h2><p class="ops-panel-description">Your current password is required when changing the email address.</p></div></div><form method="POST" action="{{ route('profile.update') }}" class="ops-stack">@csrf @method('PUT')<div class="ops-form-grid"><label class="ops-field ops-field--wide"><span class="ops-label">Name</span><input name="name" value="{{ old('name', $user->name) }}" required>@error('name')<span class="ops-error">{{ $message }}</span>@enderror</label><label class="ops-field ops-field--wide"><span class="ops-label">Email</span><input name="email" type="email" value="{{ old('email', $user->email) }}" required>@error('email')<span class="ops-error">{{ $message }}</span>@enderror</label><label class="ops-field ops-field--full"><span class="ops-label">Current password</span><input name="current_password" type="password" autocomplete="current-password">@error('current_password')<span class="ops-error">{{ $message }}</span>@enderror</label></div><div><button class="ops-button ops-button--primary">Save account changes</button></div></form></section>
                <section class="ops-panel ops-panel--padded"><div class="ops-panel-header"><div><h2 class="ops-panel-title">Change password</h2><p class="ops-panel-description">Use a unique password that is not reused on other services.</p></div></div><form method="POST" action="{{ route('profile.password.update') }}" class="ops-stack">@csrf @method('PUT')<div class="ops-form-grid"><label class="ops-field ops-field--full"><span class="ops-label">Current password</span><input name="current_password" type="password" autocomplete="current-password" required></label><label class="ops-field ops-field--wide"><span class="ops-label">New password</span><input name="password" type="password" autocomplete="new-password" required>@error('password')<span class="ops-error">{{ $message }}</span>@enderror</label><label class="ops-field ops-field--wide"><span class="ops-label">Confirm new password</span><input name="password_confirmation" type="password" autocomplete="new-password" required></label></div><div><button class="ops-button ops-button--primary">Change password</button></div></form></section>
            </div>
            <aside class="ops-stack">
                <section class="ops-panel ops-panel--padded"><div class="ops-panel-header"><div><h2 class="ops-panel-title">Two-factor authentication</h2><p class="ops-panel-description">Authenticator status and fallback readiness.</p></div><span class="ops-badge ops-badge--green">Enabled</span></div><dl class="ops-detail-grid"><div class="ops-detail-item"><dt>Configured</dt><dd>{{ $user->mfa_enabled_at?->format('F j, Y') }}</dd></div><div class="ops-detail-item"><dt>Email fallback</dt><dd>{{ $maskedEmail }} · {{ $user->email_verified_at ? 'Verified' : 'Verification required' }}</dd></div><div class="ops-detail-item"><dt>Recovery codes</dt><dd>{{ $recoveryCodesRemaining }} remaining</dd></div></dl></section>
                <section class="ops-panel ops-panel--padded"><div class="ops-panel-header"><div><h2 class="ops-panel-title">Replace authenticator</h2><p class="ops-panel-description">The current authenticator remains valid until replacement is confirmed.</p></div></div><form method="POST" action="{{ route('profile.mfa.replace.start') }}" class="ops-stack">@csrf<label class="ops-field"><span class="ops-label">Current password</span><input name="current_password" type="password" autocomplete="current-password" required></label><label class="ops-field"><span class="ops-label">Current six-digit code</span><input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></label><button class="ops-button ops-button--secondary">Replace authenticator</button></form></section>
                <section class="ops-panel ops-panel--padded ops-danger-zone"><div class="ops-panel-header"><div><h2 class="ops-panel-title">Regenerate recovery codes</h2><p class="ops-panel-description">This immediately invalidates every existing code and recovery file.</p></div></div><form method="POST" action="{{ route('profile.mfa.recovery-codes') }}" class="ops-stack">@csrf<label class="ops-field"><span class="ops-label">Current password</span><input name="current_password" type="password" autocomplete="current-password" required></label><label class="ops-field"><span class="ops-label">Current six-digit code</span><input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></label><button class="ops-button ops-button--danger">Regenerate recovery codes</button></form></section>
            </aside>
        </div>
    </div>
</x-layouts.app>
