<x-layouts.app title="Application Request Spikes - INTSEC" wide>
    <header><p class="text-xs uppercase tracking-[0.2em] text-cyan-400">{{ $monitoringSource->label() }} monitoring</p><h1 class="mt-2 text-3xl font-semibold text-white">Application request spikes</h1><p class="mt-2 max-w-3xl text-sm text-zinc-400">Request-volume monitoring from {{ $monitoringSource->label() }} HTTP telemetry after TLS termination. This is not network-layer DDoS detection.</p></header>
    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <x-security.metric-card label="Current hour" :value="number_format($currentRequests)" />
        <x-security.metric-card label="24-hour peak" :value="number_format($peakRequests)" tone="amber" />
        <x-security.metric-card label="Threshold" :value="number_format($spikeThreshold)" tone="zinc" />
        <x-security.metric-card label="Spike buckets" :value="number_format($suspiciousSpikes)" tone="red" />
    </section>
    <section class="mt-6 rounded-lg border border-zinc-800 bg-zinc-900/60 p-5"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="font-semibold text-white">Requests by hour</h2><p class="text-sm text-zinc-500">Last 24 hours</p></div><div class="text-xs text-zinc-500">4xx: {{ number_format($clientErrorCount) }} · 5xx: {{ number_format($serverErrorCount) }}</div></div><div class="mt-5 h-80"><canvas id="requestVolume"></canvas></div></section>
    <section class="mt-6 grid gap-4 lg:grid-cols-2">
        <div class="rounded-lg border border-zinc-800 bg-zinc-900/60 p-5"><h2 class="font-semibold text-white">Top source IPs</h2><div class="mt-3 divide-y divide-zinc-800">@forelse ($topIps as $row)<div class="flex justify-between py-3 text-sm"><span class="font-mono text-zinc-300">{{ $row->ip_address }}</span><span class="text-zinc-500">{{ number_format($row->total) }}</span></div>@empty<p class="py-6 text-sm text-zinc-500">No request telemetry.</p>@endforelse</div></div>
        <div class="rounded-lg border border-zinc-800 bg-zinc-900/60 p-5"><h2 class="font-semibold text-white">Top routes and paths</h2><div class="mt-3 divide-y divide-zinc-800">@forelse ($topRoutes as $row)<div class="flex justify-between gap-4 py-3 text-sm"><span class="min-w-0 truncate font-mono text-zinc-300">{{ $row->path }}</span><span class="text-zinc-500">{{ number_format($row->total) }}</span></div>@empty<p class="py-6 text-sm text-zinc-500">No request telemetry.</p>@endforelse</div></div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>new Chart(document.getElementById('requestVolume'),{type:'line',data:{labels:@json($hourlyTrend->pluck('label')),datasets:[{data:@json($hourlyTrend->pluck('count')),borderColor:'#22d3ee',backgroundColor:'rgba(34,211,238,.12)',fill:true,tension:.3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#71717a'},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#71717a',precision:0},grid:{color:'rgba(255,255,255,.06)'}}}}});</script>
</x-layouts.app>
