<x-layouts.app title="IP management - INTSEC" realtime-entities="blocked_ip">
    <div class="ops-page">
        <x-ui.page-header kicker="Enforcement policy" title="IP management" description="Centralized application-level ALLOW and BLOCK policy. BLOCK takes precedence; allowed addresses remain monitored and audited.">
            <x-slot:context><span class="ops-context-pill ops-context-pill--live">Policy enforcement active</span><span class="ops-context-pill">Current IP: <span class="ops-technical">{{ $myIp }}</span></span></x-slot:context>
            <x-slot:actions><button type="button" class="ops-button ops-button--primary" data-modal-trigger="create-ip-rule-modal">Add IP rule</button></x-slot:actions>
        </x-ui.page-header>

        @if ($errors->any())<div class="ops-banner ops-banner--danger" role="alert"><div><strong>Rule was not saved.</strong><ul class="mt-2 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif
        @if (session('status'))<div class="ops-banner ops-banner--success" role="status">IP policy was updated successfully.</div>@endif
        @if (session('self_block_warning'))<div class="ops-banner ops-banner--warning" role="alert">This rule matches your current address, <span class="ops-technical">{{ $myIp }}</span>. Explicit self-block confirmation is required.</div>@endif

        @php
            $stats = [
                ['label' => 'Total rules', 'value' => $summary['total'], 'context' => 'Stored policy records'],
                ['label' => 'Allow rules', 'value' => $summary['allowed'], 'context' => 'Still monitored'],
                ['label' => 'Block rules', 'value' => $summary['blocked'], 'context' => 'Deny wins'],
                ['label' => 'Active rules', 'value' => $summary['active'], 'context' => 'Currently enforcing'],
                ['label' => 'Expiring soon', 'value' => $summary['expiring_soon'], 'context' => 'Within 24 hours'],
            ];
        @endphp
        <section class="ops-kpi-grid" aria-label="IP policy summary">@foreach ($stats as $stat)<x-security.metric-card :label="$stat['label']" :value="$stat['value']" :context="$stat['context']" />@endforeach</section>

        <form method="GET" action="{{ route('ip-management.index') }}" class="ops-filter" aria-label="Filter IP rules"><div class="ops-filter-heading"><div><h2 class="ops-filter-title">Policy filters</h2><p class="ops-filter-state">Search rule targets, provenance, and enforcement state.</p></div></div><div class="ops-filter-grid">
            <label class="ops-field ops-field--search"><span class="ops-label">Search</span><input name="search" value="{{ request('search') }}" placeholder="IP, CIDR, reason, or reference"></label>
            <label class="ops-field"><span class="ops-label">Action</span><select name="action"><option value="">Allow and block</option><option value="allow" @selected(request('action') === 'allow')>Allow</option><option value="block" @selected(request('action') === 'block')>Block</option></select></label>
            <label class="ops-field"><span class="ops-label">State</span><select name="state"><option value="">All states</option><option value="active" @selected(request('state') === 'active')>Active</option><option value="expired" @selected(request('state') === 'expired')>Expired</option><option value="disabled" @selected(request('state') === 'disabled')>Disabled</option></select></label>
            <label class="ops-field"><span class="ops-label">Provenance</span><select name="source"><option value="">All sources</option>@foreach (['manual','automatic','alert','incident','system'] as $src)<option value="{{ $src }}" @selected(request('source') === $src)>{{ ucfirst($src) }}</option>@endforeach</select></label>
            <div class="ops-filter-actions"><a class="ops-button ops-button--quiet" href="{{ route('ip-management.index') }}">Clear</a><button class="ops-button ops-button--secondary">Apply filters</button></div>
        </div></form>

        <section class="ops-table-shell" aria-labelledby="policy-table-title"><div class="ops-panel-header"><div><h2 id="policy-table-title" class="ops-panel-title">IP policy rules</h2><p class="ops-panel-description">Enforcement, origin, expiration, and observed match count.</p></div></div><div class="ops-table-scroll"><table class="ops-table ops-table--xwide"><caption>Filtered application-level IP rules</caption>
            <thead><tr><th>IP / CIDR</th><th>Decision</th><th>State</th><th>Reason</th><th>Intelligence</th><th>Provenance</th><th>Expires</th><th class="ops-numeric">Matches</th><th>Actions</th></tr></thead><tbody>
            @forelse ($rules as $rule)
                @php
                    $info = $intel[$rule->id] ?? null;
                    $state = $rule->isExpired() ? 'expired' : ((! $rule->is_enabled || $rule->status !== 'active') ? 'disabled' : 'active');
                @endphp
                <tr>
                    <td><span class="ops-cell-primary ops-technical ops-wrap-anywhere">{{ $rule->ip_address }}</span>@if ($rule->name)<span class="ops-cell-meta">{{ $rule->name }}</span>@endif</td>
                    <td><span class="ops-badge {{ $rule->isAllowRule() ? 'ops-badge--green' : 'ops-badge--red' }}">{{ ucfirst($rule->action) }}</span></td>
                    <td><x-security.status-badge :status="$state" /></td>
                    <td><span class="ops-table-value" title="{{ $rule->description }}">{{ \Illuminate\Support\Str::limit($rule->reason ?: 'Not recorded', 80) }}</span></td>
                    <td>@if (is_array($info) && ($info['country'] ?? null))<span class="ops-cell-primary">{{ $info['country'] }}{{ ($info['city'] ?? null) ? ' / '.$info['city'] : '' }}</span><span class="ops-cell-meta">{{ \Illuminate\Support\Str::limit($info['isp'] ?? $info['organization'] ?? 'Provider unavailable', 45) }}</span>@else<span class="ops-cell-meta">Not available</span>@endif</td>
                    <td><span class="ops-cell-primary">{{ ucfirst($rule->source) }}</span><span class="ops-cell-meta">{{ $rule->administrator?->name ?? 'System' }}</span>@if ($rule->alert)<span class="ops-cell-meta">Alert <a class="ops-panel-link" href="{{ route('alerts.show', $rule->alert) }}">{{ $rule->alert->alert_id }}</a></span>@endif @if ($rule->incident)<span class="ops-cell-meta">Incident <a class="ops-panel-link" href="{{ route('incidents.show', $rule->incident) }}">{{ $rule->incident->incident_id }}</a></span>@endif</td>
                    <td>{{ $rule->expires_at?->format('Y-m-d H:i') ?? 'Permanent' }}</td><td class="ops-numeric">{{ number_format($rule->match_count) }}</td>
                    <td><div class="ops-action-group"><button type="button" class="ops-button ops-button--quiet" data-modal-trigger="edit-ip-rule-{{ $rule->id }}">Edit</button><form method="POST" action="{{ route('ip-management.toggle', $rule) }}" onsubmit="return confirm('{{ $rule->is_enabled ? 'Disable' : 'Enable' }} this rule?');">@csrf @method('PATCH')<input type="hidden" name="enabled" value="{{ $rule->is_enabled ? 0 : 1 }}"><button class="ops-button ops-button--quiet">{{ $rule->is_enabled ? 'Disable' : 'Enable' }}</button></form><form method="POST" action="{{ route('ip-management.destroy', $rule) }}" onsubmit="return confirm('Delete the rule for {{ $rule->ip_address }}? Enforcement will stop; the audit record remains.');">@csrf @method('DELETE')<button class="ops-button ops-button--danger">Delete</button></form></div></td>
                </tr>
            @empty<tr><td colspan="9"><x-ui.empty-state title="No IP rules found" description="No policy records match the current filters." /></td></tr>@endforelse
            </tbody></table></div><x-ui.simple-pagination :paginator="$rules" noun="rules" /></section>
    </div>

    <div id="create-ip-rule-modal" class="ops-modal" data-modal data-modal-auto-open="{{ $errors->any() && old('ip_address') ? 'true' : 'false' }}" role="dialog" aria-modal="true" aria-labelledby="create-ip-rule-title" aria-hidden="true"><div class="ops-modal-dialog"><div class="ops-modal-header"><div><p class="ops-kicker">Enforcement policy</p><h2 id="create-ip-rule-title" class="ops-panel-title">Add IP rule</h2></div><button type="button" class="ops-button ops-button--quiet" data-modal-close>Close</button></div>
        <form method="POST" action="{{ route('ip-management.store') }}" class="ops-modal-body ops-stack">@csrf
            <label class="ops-field"><span class="ops-label">IP address or CIDR <span class="ops-required">required</span></span><input class="ops-technical" name="ip_address" value="{{ old('ip_address') }}" required placeholder="203.0.113.10, 2001:db8::1, or 10.0.0.0/8"></label>
            <div class="ops-form-grid"><label class="ops-field"><span class="ops-label">Decision</span><select name="action"><option value="block" @selected(old('action') === 'block')>Block</option><option value="allow" @selected(old('action') === 'allow')>Allow</option></select></label><label class="ops-field ops-field--wide"><span class="ops-label">Reference</span><input name="name" value="{{ old('name') }}" placeholder="Optional label"></label><label class="ops-field ops-field--full"><span class="ops-label">Reason <span class="ops-required">required</span></span><input name="reason" value="{{ old('reason') }}" required></label><label class="ops-field ops-field--full"><span class="ops-label">Description</span><textarea name="description" rows="3">{{ old('description') }}</textarea></label><label class="ops-field"><span class="ops-label">Expiration</span><select name="expiration">@foreach (['permanent'=>'Permanent','30m'=>'30 minutes','1h'=>'1 hour','24h'=>'24 hours','7d'=>'7 days','30d'=>'30 days','custom'=>'Custom date'] as $value => $label)<option value="{{ $value }}" @selected(old('expiration','permanent') === $value)>{{ $label }}</option>@endforeach</select></label><label class="ops-field"><span class="ops-label">Custom expiry</span><input type="datetime-local" name="expires_at" value="{{ old('expires_at') }}"></label></div>
            <label class="ops-checkbox"><input type="checkbox" name="is_enabled" value="1" @checked(old('is_enabled', true))>Enable this rule immediately</label><label class="ops-checkbox"><input type="checkbox" name="confirm_self_block" value="1">I explicitly confirm blocking my own current IP if this rule matches <span class="ops-technical">{{ $myIp }}</span>.</label>
            <div class="ops-filter-actions"><button type="button" class="ops-button ops-button--quiet" data-modal-close>Cancel</button><button class="ops-button ops-button--primary">Create rule</button></div>
        </form></div></div>

    @foreach ($rules as $rule)
        <div id="edit-ip-rule-{{ $rule->id }}" class="ops-modal" data-modal role="dialog" aria-modal="true" aria-labelledby="edit-ip-rule-title-{{ $rule->id }}" aria-hidden="true"><div class="ops-modal-dialog"><div class="ops-modal-header"><div><p class="ops-kicker">Edit policy rule</p><h2 id="edit-ip-rule-title-{{ $rule->id }}" class="ops-panel-title ops-technical ops-wrap-anywhere">{{ $rule->ip_address }}</h2></div><button type="button" class="ops-button ops-button--quiet" data-modal-close>Close</button></div>
            <form method="POST" action="{{ route('ip-management.update', $rule) }}" class="ops-modal-body ops-stack">@csrf @method('PUT')<div class="ops-form-grid"><label class="ops-field"><span class="ops-label">Decision</span><select name="action"><option value="block" @selected($rule->action === 'block')>Block</option><option value="allow" @selected($rule->action === 'allow')>Allow</option></select></label><label class="ops-field ops-field--wide"><span class="ops-label">Reference</span><input name="name" value="{{ $rule->name }}"></label><label class="ops-field ops-field--full"><span class="ops-label">Reason</span><input name="reason" value="{{ $rule->reason }}" required></label><label class="ops-field ops-field--full"><span class="ops-label">Description</span><textarea name="description" rows="3">{{ $rule->description }}</textarea></label><label class="ops-field"><span class="ops-label">Expiration</span><select name="expiration"><option value="permanent" @selected(! $rule->expires_at)>Permanent</option><option value="30m">30 minutes</option><option value="1h">1 hour</option><option value="24h">24 hours</option><option value="7d">7 days</option><option value="30d">30 days</option><option value="custom" @selected((bool) $rule->expires_at)>Custom date</option></select></label><label class="ops-field"><span class="ops-label">Custom expiry</span><input type="datetime-local" name="expires_at" value="{{ $rule->expires_at?->format('Y-m-d\TH:i') }}"></label></div><label class="ops-checkbox"><input type="checkbox" name="is_enabled" value="1" @checked($rule->is_enabled)>Rule enabled</label><label class="ops-checkbox"><input type="checkbox" name="confirm_self_block" value="1">I explicitly confirm blocking my current IP if this change matches <span class="ops-technical">{{ $myIp }}</span>.</label><div class="ops-filter-actions"><button type="button" class="ops-button ops-button--quiet" data-modal-close>Cancel</button><button class="ops-button ops-button--primary">Save changes</button></div></form>
        </div></div>
    @endforeach
</x-layouts.app>
