<x-layouts.app title="IP Intelligence - INTSEC" wide realtime-entities="request_activity,blocked_ip" :realtime-source="$monitoringSource->value">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs uppercase tracking-[0.2em] text-cyan-400">{{ $monitoringSource->label() }} IP intelligence</p><h1 class="mt-2 text-3xl font-semibold text-white">IP locations</h1><p class="mt-2 max-w-3xl text-sm text-zinc-400">Approximate public-IP enrichment for {{ $monitoringSource->label() }} activity. Private, reserved, and loopback addresses remain visible but are never plotted.</p></div><div class="flex gap-2 text-xs text-zinc-400"><span class="rounded border border-zinc-800 px-2 py-1">Page IPs {{ $ipLocations->count() }}</span><span class="rounded border border-zinc-800 px-2 py-1">Countries {{ $countryCount }}</span><span class="rounded border border-zinc-800 px-2 py-1">Cities {{ $cityCount }}</span></div></header>
    <form method="GET" class="mt-6 grid gap-3 rounded-lg border border-zinc-800 bg-zinc-900/60 p-4 sm:grid-cols-5"><input name="search" value="{{ request('search') }}" placeholder="Search IP or location" class="rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><input name="ip" value="{{ request('ip') }}" placeholder="IP contains…" class="rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><select name="ip_type" class="rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><option value="">All IP types</option>@foreach (['public','private','loopback','reserved','invalid'] as $type)<option value="{{ $type }}" @selected(request('ip_type')===$type)>{{ ucfirst($type) }}</option>@endforeach</select><select name="country" class="rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm"><option value="">All countries</option>@foreach ($countries as $code=>$country)<option value="{{ $code }}" @selected(request('country')===$code)>{{ $country }}</option>@endforeach</select><div class="flex gap-2"><button class="flex-1 rounded-md bg-cyan-400 px-3 py-2 text-sm font-semibold text-zinc-950">Filter</button><a href="{{ auth()->user()->isAdministrator() ? route('monitoring.ip-locations', $monitoringSource->value) : route('ip-locations') }}" class="rounded-md border border-zinc-700 px-3 py-2 text-sm">Clear</a></div></form>
    <section class="mt-6 rounded-lg border border-zinc-800 bg-zinc-900/60 p-4"><div id="ip-location-map" class="h-[clamp(320px,55vh,650px)] w-full rounded-md border border-zinc-800"></div><div id="ip-location-empty" class="hidden py-10 text-center text-sm text-zinc-500">No public IPs with valid coordinates are available on this page.</div></section>
    <section class="mt-6 overflow-hidden rounded-lg border border-zinc-800 bg-zinc-900/60"><div class="overflow-x-auto"><table class="min-w-[1100px] w-full text-left text-sm"><thead class="border-b border-zinc-800 text-xs uppercase tracking-wider text-zinc-500"><tr><th class="px-4 py-3">IP</th><th class="px-4 py-3">Type</th><th class="px-4 py-3">Approximate location</th><th class="px-4 py-3">ASN / organization</th><th class="px-4 py-3">Last seen</th><th class="px-4 py-3">Requests</th><th class="px-4 py-3">Policy</th></tr></thead><tbody class="divide-y divide-zinc-800">@forelse ($ipLocations as $row)<tr><td class="px-4 py-3 font-mono text-zinc-200">{{ $row['ip'] }}</td><td class="px-4 py-3">{{ ucfirst($row['ip_type']) }}</td><td class="px-4 py-3 text-zinc-400">@if ($row['ip_type']==='loopback') Localhost @elseif ($row['ip_type']==='private') Private network @elseif ($row['ip_type']!=='public') No public geolocation @else {{ collect([$row['city'],$row['region'],$row['country']])->filter()->join(', ') ?: 'Awaiting enrichment' }} @endif</td><td class="px-4 py-3 text-zinc-400">{{ $row['asn'] ? 'AS'.$row['asn'].' · ' : '' }}{{ $row['organization'] ?? $row['isp'] ?? 'Unknown' }}</td><td class="px-4 py-3 text-zinc-400">{{ \Carbon\Carbon::parse($row['last_seen'])->diffForHumans() }}</td><td class="px-4 py-3">{{ number_format($row['event_count']) }}</td><td class="px-4 py-3 {{ $row['is_blocked'] ? 'text-red-300' : 'text-zinc-500' }}">{{ $row['is_blocked'] ? 'Blocked' : 'No block' }}</td></tr>@empty<tr><td colspan="7" class="px-4 py-10 text-center text-zinc-500">No observed IPs match these filters.</td></tr>@endforelse</tbody></table></div></section><div class="mt-6">{{ $ipLocations->links() }}</div>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script>
        const locations = @json($mapLocations);
        const mapNode = document.getElementById('ip-location-map');
        const emptyNode = document.getElementById('ip-location-empty');
        if (window.L && locations.length) {
            const map = L.map(mapNode).setView([15, 0], 2);
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
            const bounds = [];
            locations.forEach((entry) => {
                const lat=Number(entry.latitude), lng=Number(entry.longitude);
                if (!Number.isFinite(lat)||!Number.isFinite(lng)||(lat===0&&lng===0)) return;
                const popup=document.createElement('div'); popup.style.color='#111827'; popup.style.minWidth='210px';
                const lines=[['IP',entry.ip],['Approximate location',[entry.city,entry.country].filter(Boolean).join(', ')||'Unknown'],['ASN / organization',[entry.asn?'AS'+entry.asn:null,entry.organization||entry.isp].filter(Boolean).join(' · ')||'Unknown'],['Last seen',entry.last_seen?new Date(entry.last_seen).toLocaleString():'Unknown'],['Requests',String(entry.event_count||0)],['Policy',entry.is_blocked?'Blocked':'No block']];
                lines.forEach(([label,value])=>{const row=document.createElement('div');const strong=document.createElement('strong');strong.textContent=label+': ';row.appendChild(strong);row.appendChild(document.createTextNode(value));popup.appendChild(row);});
                L.marker([lat,lng]).addTo(map).bindPopup(popup); bounds.push([lat,lng]);
            });
            if (bounds.length===1) map.setView(bounds[0],5); else if(bounds.length) map.fitBounds(bounds,{padding:[30,30]});
            if(!bounds.length){mapNode.classList.add('hidden');emptyNode.classList.remove('hidden');}
            setTimeout(()=>map.invalidateSize(),100);
        } else { mapNode.classList.add('hidden'); emptyNode.classList.remove('hidden'); }
    </script>
</x-layouts.app>
